export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_FAILURE = 'CREATE_POST_FAILURE'

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAILURE = 'DELETE_POST_FAILURE'

export const GET_NEWS_FEED_REQUEST = 'GET_NEWS_FEED_REQUEST'
export const GET_NEWS_FEED_SUCCESS = 'GET_NEWS_FEED_SUCCESS'
export const GET_NEWS_FEED_FAILURE = 'GET_NEWS_FEED_FAILURE'

export const GET_MY_POSTS_REQUEST = 'GET_MY_POSTS_REQUEST'
export const GET_MY_POSTS_SUCCESS = 'GET_MY_POSTS_SUCCESS'
export const GET_MY_POSTS_FAILURE = 'GET_MY_POSTS_FAILURE'

export const LIKE_POST_REQUEST = 'USER_LIKE_POST_REQUEST'
export const LIKE_POST_SUCCESS = 'USER_LIKE_POST_SUCCESS'
export const LIKE_POST_FAILURE = 'USER_LIKE_POST_FAILURE'
